home/urls.py
from django.conf.urls import patterns, url

from home.views import HomeView, TodoList, TodoDetail


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home_page'),
    url(r'^todos/$', TodoList.as_view(), name="todos_list"),
    url(r'^todos/(?P<pk>[0-9]+)/$', TodoDetail.as_view(), name="todos_update"),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'', include('home.urls', namespace="home")),
    url(r'^admin/', include(admin.site.urls)),
)

home/models.py
from django.db import models


class TestModel(models.Model):
    first_name = models.CharField(max_length=30)


class Todo(models.Model):
    item = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

home/views.py
from rest_framework import status
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.parsers import JSONParser
from rest_framework.views import APIView
from rest_framework.response import Response

from django.views.generic import TemplateView

from home.models import Todo
from home.serializers import TodoSerializer


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        return {"current_page_name": "Home"}


class TodoMixin(object):
    queryset = Todo.objects.all().order_by('-id')
    serializer_class = TodoSerializer
    parser_classes = (JSONParser,)


class TodoList(TodoMixin, ListCreateAPIView):
    """Return a list of all the todos, or create new ones."""
    pass


class TodoDetail(TodoMixin, RetrieveUpdateDestroyAPIView):
    """Return a specific todo, update it, or delete it."""
    pass

home/static_src/templates/todoApp.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="#">ng-todo</a>
        <a class="navbar-right navbar-img" href="#"><img src="/static/img/AngularJS.png" alt=""></a>
    </div>
</div>

<section ng-controller="NgTodoController as ctrl"><!-- ctrl -->
    <div class="outer-container">

        <div class="add-todo-group input-group input-group-lg">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-list-alt"></i>
            </span>
            <input ng-model="ctrl.todoData.newTask" placeholder="Add a new todo here!" class="form-control" type="text"><!-- model  -->
            <span class="input-group-btn">
                <button class="btn btn-success" type="button" ng-click="ctrl.addNewTask()"><!-- click  -->
                    <i class="glyphicon glyphicon-plus"></i>
                </button>
            </span>
        </div>

        <div class="input-group input-group-lg" ng-repeat="todo in ctrl.todoData.todos"><!-- repeat  -->
            <span class="input-group-addon">
                <input ng-model="todo.is_done" ng-click="ctrl.updateTodoItem(todo)" type="checkbox"> <!-- model -->
            </span>
            <input class="form-control" type="text" ng-model="todo.item" ng-model-options="{ updateOn: 'default blur', debounce: {'default': 500, 'blur': 0} }" ng-change="ctrl.updateTodoItem(todo)" ng-class="{finished: todo.is_done}"><!-- model / class  -->
            <span class="input-group-btn">
                <button class="btn btn-danger" type="button" ng-click="ctrl.removeTodo($index, todo.id)"><!-- click  -->
                    <i class="glyphicon glyphicon-remove"></i>
                </button>
            </span>
        </div>

        <div class="btn-clear-group">
            <button class="btn btn-primary btn-clear" ng-click="ctrl.clearCompleted()">Clear Completed</button><!-- click -->
        </div>
    </div>
</section>

home/templates/home.html
{% load staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static "exampleApp/css/exampleApp.dist.css" %}">
    <script src="{% static "exampleApp/js/exampleApp.dist.js" %}"></script>
{% endblock extra_head %}

{% block main_content %}
  <div ng-app="ToDoApp">
    <div ng-view></div>
  </div>

{% endblock main_content %}

{% block extra_javascript %}

  <script>
    // Bootstrap Django data for angular
    window.jsBootstrap = {};
    window.jsBootstrap.todoListUrl = "{% url "home:todos_list" %}";
    window.jsBootstrap.todoUpdateUrl = "{% url "home:todos_update" pk=0 %}";
    window.jsBootstrap.staticUrl = "{% static "" %}";
  </script>
{% endblock %}